-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ProfunctorIo.Object exposing (..)


type AuthPayload
    = AuthPayload


type Downvotes_by_submitters
    = Downvotes_by_submitters


type Jobs
    = Jobs


type Jobs_mutation_response
    = Jobs_mutation_response


type LogoutResponse
    = LogoutResponse


type Mutation
    = Mutation


type Query
    = Query


type Submits_by_users
    = Submits_by_users


type Upvotes_by_submitters
    = Upvotes_by_submitters


type UserData
    = UserData


type UserResume
    = UserResume


type Waitlist_resume_mutation_response
    = Waitlist_resume_mutation_response
