-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ProfunctorIo.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import ProfunctorIo.Scalar exposing (defaultCodecs)


type alias Bigint =
    ProfunctorIo.Scalar.Bigint


type alias Id =
    ProfunctorIo.Scalar.Id


type alias Timestamptz =
    ProfunctorIo.Scalar.Timestamptz


type alias Upload =
    ProfunctorIo.Scalar.Upload


type alias Uuid =
    ProfunctorIo.Scalar.Uuid


codecs : ProfunctorIo.Scalar.Codecs Bigint Id Timestamptz Upload Uuid
codecs =
    ProfunctorIo.Scalar.defineCodecs
        { codecBigint = defaultCodecs.codecBigint
        , codecId = defaultCodecs.codecId
        , codecTimestamptz = defaultCodecs.codecTimestamptz
        , codecUpload = defaultCodecs.codecUpload
        , codecUuid = defaultCodecs.codecUuid
        }
