-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ProfunctorIo.Enum.Downvotes_by_submitters_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "downvotes\_by\_submitters"

  - Count - column name
  - Submitted\_by\_username - column name

-}
type Downvotes_by_submitters_select_column
    = Count
    | Submitted_by_username


list : List Downvotes_by_submitters_select_column
list =
    [ Count, Submitted_by_username ]


decoder : Decoder Downvotes_by_submitters_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "count" ->
                        Decode.succeed Count

                    "submitted_by_username" ->
                        Decode.succeed Submitted_by_username

                    _ ->
                        Decode.fail ("Invalid Downvotes_by_submitters_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Downvotes_by_submitters_select_column -> String
toString enum____ =
    case enum____ of
        Count ->
            "count"

        Submitted_by_username ->
            "submitted_by_username"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Downvotes_by_submitters_select_column
fromString enumString____ =
    case enumString____ of
        "count" ->
            Just Count

        "submitted_by_username" ->
            Just Submitted_by_username

        _ ->
            Nothing
