-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ProfunctorIo.Object.AuthPayload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ProfunctorIo.InputObject
import ProfunctorIo.Interface
import ProfunctorIo.Object
import ProfunctorIo.Scalar
import ProfunctorIo.ScalarCodecs
import ProfunctorIo.Union


access_token : SelectionSet String ProfunctorIo.Object.AuthPayload
access_token =
    Object.selectionForField "String" "access_token" [] Decode.string


user_id : SelectionSet ProfunctorIo.ScalarCodecs.Id ProfunctorIo.Object.AuthPayload
user_id =
    Object.selectionForField "ScalarCodecs.Id" "user_id" [] (ProfunctorIo.ScalarCodecs.codecs |> ProfunctorIo.Scalar.unwrapCodecs |> .codecId |> .decoder)
