-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ProfunctorIo.Object.Submits_by_users exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ProfunctorIo.InputObject
import ProfunctorIo.Interface
import ProfunctorIo.Object
import ProfunctorIo.Scalar
import ProfunctorIo.ScalarCodecs
import ProfunctorIo.Union


count : SelectionSet (Maybe ProfunctorIo.ScalarCodecs.Bigint) ProfunctorIo.Object.Submits_by_users
count =
    Object.selectionForField "(Maybe ScalarCodecs.Bigint)" "count" [] (ProfunctorIo.ScalarCodecs.codecs |> ProfunctorIo.Scalar.unwrapCodecs |> .codecBigint |> .decoder |> Decode.nullable)


submitted_by_username : SelectionSet (Maybe String) ProfunctorIo.Object.Submits_by_users
submitted_by_username =
    Object.selectionForField "(Maybe String)" "submitted_by_username" [] (Decode.string |> Decode.nullable)
