-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ProfunctorIo.Object.UserResume exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ProfunctorIo.InputObject
import ProfunctorIo.Interface
import ProfunctorIo.Object
import ProfunctorIo.Scalar
import ProfunctorIo.ScalarCodecs
import ProfunctorIo.Union


level : SelectionSet String ProfunctorIo.Object.UserResume
level =
    Object.selectionForField "String" "level" [] Decode.string


scope : SelectionSet String ProfunctorIo.Object.UserResume
scope =
    Object.selectionForField "String" "scope" [] Decode.string


stack : SelectionSet String ProfunctorIo.Object.UserResume
stack =
    Object.selectionForField "String" "stack" [] Decode.string
