-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ProfunctorIo.Object.UserData exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ProfunctorIo.InputObject
import ProfunctorIo.Interface
import ProfunctorIo.Object
import ProfunctorIo.Scalar
import ProfunctorIo.ScalarCodecs
import ProfunctorIo.Union


first_name : SelectionSet (Maybe String) ProfunctorIo.Object.UserData
first_name =
    Object.selectionForField "(Maybe String)" "first_name" [] (Decode.string |> Decode.nullable)


id : SelectionSet String ProfunctorIo.Object.UserData
id =
    Object.selectionForField "String" "id" [] Decode.string


last_name : SelectionSet (Maybe String) ProfunctorIo.Object.UserData
last_name =
    Object.selectionForField "(Maybe String)" "last_name" [] (Decode.string |> Decode.nullable)


photo_url : SelectionSet (Maybe String) ProfunctorIo.Object.UserData
photo_url =
    Object.selectionForField "(Maybe String)" "photo_url" [] (Decode.string |> Decode.nullable)


tg_id : SelectionSet String ProfunctorIo.Object.UserData
tg_id =
    Object.selectionForField "String" "tg_id" [] Decode.string


user_resume :
    SelectionSet decodesTo ProfunctorIo.Object.UserResume
    -> SelectionSet (Maybe decodesTo) ProfunctorIo.Object.UserData
user_resume object____ =
    Object.selectionForCompositeField "user_resume" [] object____ (Basics.identity >> Decode.nullable)


username : SelectionSet (Maybe String) ProfunctorIo.Object.UserData
username =
    Object.selectionForField "(Maybe String)" "username" [] (Decode.string |> Decode.nullable)
